# Generated by Django 4.2.9 on 2024-01-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
